### ISSUE TITLE
remote-if.py must be rewritten for modern Tornado

### ISSUE THREAD

**Issue by GwynethLlewelyn** [erkyrath/remote-if-demo#2]
Hi,

Shiny, brand-new Glk newbie here, who refuses to learn Python properly (we all have our quirks...).

I'm fascinated with the possibilities of RemGlk, so I wanted to try it out using whatever 'recommended' method you had. Apparently, starting with this repo should get me started. Cool, but now I'm stumped with complex Python errors, which are beyond my ability to fix them.

I'm running macOS Big Sur 11.4 Beta (20F5065a), Python 3.9.5 (installed via Homebrew), and Tornado 6.1 (installed via `pip`).

```sh
$ python3 remote-if.py --debug --command='../glulxe/glulxe ../Game\ Files/advent.ulx'
[I 210510 20:41:38 web:2239] 200 GET / (::1) 4.49ms
[I 210510 20:41:41 remote-if:108] Created session object <Session "5e8fc4e5a17b2608c1fe8c5da80135b7">
[I 210510 20:41:41 web:2239] 304 GET /play (::1) 7.18ms
[I 210510 20:41:41 remote-if:207] Launching game for <Session "5e8fc4e5a17b2608c1fe8c5da80135b7">
[E 210510 20:41:41 web:1789] Uncaught exception POST /play (::1)
    HTTPServerRequest(protocol='http', host='localhost:4000', method='POST', uri='/play', version='HTTP/1.1', remote_ip='::1')
    Traceback (most recent call last):
      File "/usr/local/lib/python3.9/site-packages/tornado/web.py", line 1704, in _execute
        result = await result
      File "/usr/local/lib/python3.9/site-packages/tornado/gen.py", line 234, in wrapper
        yielded = ctx_run(next, result)
      File "/Users/gwyneth/Developer/VirtualGrue/remote-if-demo/remote-if.py", line 124, in post
        session.launch()
      File "/Users/gwyneth/Developer/VirtualGrue/remote-if-demo/remote-if.py", line 215, in launch
        self.proc.stdout.read_until_close(
    TypeError: read_until_close() takes 1 positional argument but 3 were given
```

When I saw on the Python source that `read_until_close()` is actually passing _two_ arguments (neither 1 nor 3), I said to myself, 'ok, I _really_ don't understand enough Python to fix _this_ and need some help' 😹 

Note: _VirtualGrue_ (mentioned on the log) is my upcoming experiment to communicate with `gluxle`. No, it won't be written in Python...

**Comment by erkyrath** [comment]
I haven't tested this code for several years. Meaning several releases of Python and Tornado. So it's likely that something has changed behind the scenes and my code is out of date.

I'll try to take a look this weekend.

**Comment by erkyrath** [comment]
Yeah, Tornado 6.1 is very different from 3.1.1. I'm afraid the remote-if.py script needs to be rewritten with a modern async idiom. I don't have the bandwidth for that at present.

**Comment by GwynethLlewelyn** [comment]
Don't worry, I guess that if nobody else has 'complained' so far, it's not really important...

As said, I was just trying to get some inspiration to essentially replicate the same functionality, but using [Go](https://golang.org/) instead (we all have our own preferences!) — but I guess that Python is really too idiomatic for me to use it as 'inspiration'...

Anyway, thanks for looking into it, even if it's neither urgent, nor important!

**Comment by erkyrath** [comment]
I understand that Go has solid support for async idioms, so this should be easy enough. You're just starting a background process and throwing in blocks of text (JSON stanzas). Then, as text comes *out* of the process, keep accumulating it until it parses as a complete JSON stanza.

**Comment by GwynethLlewelyn** [comment]
You couldn't have summarised it better 😁 

Let's just say that there are a few issues to figure out when having just _one_ process but expecting _several_ people to run the game simultaneously (each getting separate input/output queues, of course). The single-user play seems straightforward enough, though.
